---

- name: Cisco Intersight Create
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files: main.yml
  tasks:


  ## SERVERS

    # - name: Claim new Server
    #   cisco.intersight.intersight_target_claim:
    #     api_uri: "{{ intersight_endpoint }}"
    #     api_private_key: "{{ intersight_privatekey }}"
    #     api_key_id: "{{ intersight_apikeyid }}"
    #     device_id: "{{ device_id }}"
    #     claim_code: "{{ claim_code }}"
    #     state: present

    - name: Get info for all servers
      cisco.intersight.intersight_info:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        server_names:

  ## POOLS

    - name: Create IP Pool
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /ippool/Pools
        query_params:
          $filter: "Name eq 'dc1-ip-pool'"
        api_body: {
          "Name": "dc1-ip-pool",
          "Description": "DC1 IP Pool",
          "IpV4Config": {
            "Netmask": "255.255.255.0",
            "Gateway": "10.0.0.1",
            "PrimaryDns": "8.8.8.8",
            "SecondaryDns": "8.8.8.9"
            },
          "IpV4Blocks": [ 
            {
              "From": "10.0.0.2",
              "Size": 100
            }
            ],
          "AssignmentOrder": "default"
        }
        state: present
      register: test

  ## POLICIES

    - name: Create Local User Policy
      cisco.intersight.intersight_local_user_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: local-user-policy
        description: Local User Policy
        local_users:
          - username: user1
            role: readonly
            password: password
        state: present

    - name: Create BIOS Policy
      cisco.intersight.intersight_bios_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: bios-policy
        description: BIOS Policy        
        processor_cstate: enabled
        cdn_enable: enabled
        cpu_energy_performance: performance
        direct_cache_access: enabled
        state: present

    - name: Create Boot Order Policy
      cisco.intersight.intersight_boot_order_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: boot-order-policy
        description: Boot Order Policy
        configured_boot_mode: Legacy
        boot_devices:
          - device_type: Local Disk
            device_name: Boot-Lun
            controller_slot: MRAID
        state: present

    - name: Create NTP Policy
      cisco.intersight.intersight_ntp_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: ntp-policy 
        description: NTP Policy
        ntp_servers:
          - ntp.esl.cisco.com
        timezone: Europe/Lisbon
        state: present
        
    - name: Create IMC Access Policy
      cisco.intersight.intersight_imc_access_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: imc-access-policy
        description: IMC Access Policy
        ip_pool: dc1-ip-pool
        vlan_id: 10
        state: present

    - name: Create Virtual Media Policy
      cisco.intersight.intersight_virtual_media_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: virtual-media-policy
        description: Virutal Media Policy
        cdd_virtual_media:
          mount_type: nfs
          mount_options: ro
          password: ''
          username: ''
          volume: nfs-cdd
          remote_hostname: '10.11.12.13'
          remote_path: 'mnt/SHARE/ISOS/RHEL'
          remote_file: 'RHEL10.iso'
        hdd_virtual_media:
          mount_type: nfs
          mount_options: rw
          password: ''
          username: ''
          volume: nfs-hdd
          remote_hostname: 10.11.12.13
          remote_path: mnt/SHARE/ISOS/RHEL
          remote_file: RHEL10.img
        state: present


  ## PROFILES

    - name: Create Server Profile
      cisco.intersight.intersight_server_profile:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: sp-server
        target_platform: FIAttached
        description: Profile for Servers
        # assigned_server: 5e3b517d6176752d319a9999
        boot_order_policy: boot-order-policy
        imc_access_policy: -imc-access-policy
        local_user_policy: local-user-policy
        ntp_policy: ntp-policy
        virtual_media_policy: virtual-media-policy
        # storage_policy: storage
        # lan_connectivity_policy: sjc02-d23-lan
        state: present

