---

- name: Cisco Intersight Delete
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files: main.yml
  tasks:

  ## SERVERS

    # - name: Delete Server Claim
    #   cisco.intersight.intersight_target_claim:
    #     api_uri: "{{ intersight_endpoint }}"
    #     api_private_key: "{{ intersight_privatekey }}"
    #     api_key_id: "{{ intersight_apikeyid }}"
    #     device_id: "{{ device_id }}"
    #     claim_code: "{{ claim_code }}"
    #     state: absent


  ## TEMPLATES

    - name: Delete Profile Template
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /server/ProfileTemplates
        query_params:
          $filter: "Name eq 'server-profile-template'"
        state: absent


  ## PROFILES

    - name: Delete Server Profile
      cisco.intersight.intersight_server_profile:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: sp-server
        state: absent


  ## POLICIES

    - name: Delete Local User Policy
      cisco.intersight.intersight_local_user_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: local-user-policy
        state: absent

    - name: Delete BIOS Policy
      cisco.intersight.intersight_bios_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: bios-policy
        description: BIOS Policy        
        state: absent

    - name: Delete Boot Order Policy
      cisco.intersight.intersight_boot_order_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: boot-order-policy
        state: absent

    - name: Delete NTP Policy
      cisco.intersight.intersight_ntp_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: ntp-policy 
        state: absent

    - name: Delete IMC Access Policy
      cisco.intersight.intersight_imc_access_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: imc-access-policy
        ip_pool: dc1-ip-pool
        vlan_id: 10
        state: absent

    - name: Delete Virtual Media Policy
      cisco.intersight.intersight_virtual_media_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: virtual-media-policy
        state: absent


  ## POOLS

    - name: Delete IP Pool
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /ippool/Pools
        name: 'dc1-ip-pool'
        state: absent

