---

- name: Cisco Intersight
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files: main.yml
  tasks:

    - name: Get info for all servers
      cisco.intersight.intersight_info:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        #server_names:
        
    - name: Debug intersight all servers 
      ansible.builtin.debug:
        msg: "server name {{ item.Name }}, moid {{ item.Moid }}"
      loop: "{{ intersight_servers }}"
      when: intersight_servers is defined

    - name: Configure Local User Policy
      cisco.intersight.intersight_local_user_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: local-user-policy
        description: local-user-policy
        local_users:
          - username: user1
            role: readonly
            password: password
          - username: user2
            role: readonly
            password: password
        state: present

    - name: Configure Server Profile
      cisco.intersight.intersight_server_profile:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: SP-Server1
        target_platform: FIAttached
        description: Profile for Server1
        # assigned_server: 5e3b517d6176752d319a9999
        # boot_order_policy: COS-Boot
        # imc_access_policy: sjc02-d23-access
        # lan_connectivity_policy: sjc02-d23-lan
        # local_user_policy: guest-admin
        # ntp_policy: lab-ntp
        # storage_policy: storage
        # virtual_media_policy: COS-VM