---

- name: Cisco Intersight
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files: main.yml
  tasks:

    - debug:
        var: intersight_apikeyid

    - debug:
        var: intersight_privatekey

    - name: Get info for all servers
      cisco.intersight.intersight_info:
        #api_uri: "https://intersight.com/api/v1"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        server_names:
        
    - name: Debug intersight_servers
      ansible.builtin.debug:
        msg: "server name {{ item.Name }}, moid {{ item.Moid }}"
      loop: "{{ intersight_servers }}"
      when: intersight_servers is defined