---

- name: Cisco Intersight Delete
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files: main.yml
  tasks:

  ## SERVERS


  ## TEMPLATES

    - name: Query Server Profile Template
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /server/ProfileTemplates
        query_params:
          $filter: "Name eq 'server-profile-template'"
      register: server_profile_templates


  ## PROFILES

    - name: Query Server Profile
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /server/Profiles
        query_params:
          $filter: "Name eq 'server-profile'"
      register: server_profiles


  ## POLICIES

    # - name: Query Local User Policy
    #   cisco.intersight.intersight_rest_api:
    #     api_uri: "{{ intersight_endpoint }}"
    #     api_private_key: "{{ intersight_privatekey }}"
    #     api_key_id: "{{ intersight_apikeyid }}"
    #     resource_path: /iam/Policies
    #     query_params:
    #       $filter: "Name eq 'local-user-policy'"

    - name: Query BIOS Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /bios/Policies
        query_params:
          $filter: "Name eq 'bios-policy'"

    - name: Query Boot Order Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: boot-order-policy

    - name: Query NTP Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /ntp/Policies
        query_params:
          $filter: "Name eq 'ntp-policy'"

    - name: Query IMC Access Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /access/Policies
        query_params:
          $filter: "Name eq 'imc-access-policy'"

    - name: Query Virtual Media Policy
      cisco.intersight.intersight_virtual_media_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /vmedia/Policies
        query_params:
          $filter: "Name eq 'virtual-media-policy'"


  ## POOLS

    - name: Query IP Pools
      cisco.intersight.intersight_server_profile:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        query_params:
          $filter: "Name eq '*'"
      register: sp_server
