---

- name: Cisco Intersight Delete
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files: main.yml
  tasks:

  ## SERVERS


  ## TEMPLATES

    - name: Query Server Profile Template
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /server/ProfileTemplates
        query_params:
          $filter: "Name eq 'server-profile-template'"
      register: server_profile_templates


  ## PROFILES

    - name: Query Server Profile
      cisco.intersight.intersight_server_profile:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /server/ProfileTemplates
        query_params:
          $filter: "Name eq 'server-profile'"
      register: server_profiles


  ## POLICIES

    - name: Query Local User Policy
      cisco.intersight.intersight_local_user_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: local-user-policy
        state: absent

    - name: Query BIOS Policy
      cisco.intersight.intersight_bios_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: bios-policy
        description: BIOS Policy        
        state: absent

    - name: Query Boot Order Policy
      cisco.intersight.intersight_boot_order_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: boot-order-policy
        state: absent

    - name: Query NTP Policy
      cisco.intersight.intersight_ntp_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: ntp-policy 
        state: absent

    - name: Query IMC Access Policy
      cisco.intersight.intersight_imc_access_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: imc-access-policy
        ip_pool: dc1-ip-pool
        vlan_id: 10
        state: absent

    - name: Query Virtual Media Policy
      cisco.intersight.intersight_virtual_media_policy:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        name: virtual-media-policy
        state: absent


  ## POOLS

    - name: Query IP Pools
      cisco.intersight.intersight_server_profile:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        query_params:
          $filter: "Name eq '*'"
      register: sp_server
