---

- name: Cisco Intersight Delete
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files: main.yml
  tasks:

  ## SERVERS


  ## TEMPLATES

    - name: Query Server Profile Template
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /server/ProfileTemplates
        query_params:
          $filter: "Name eq 'server-profile-template'"
      register: server_profile_templates


  ## PROFILES

    - name: Query Server Profile
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /server/Profiles
        query_params:
          $filter: "Name eq 'server-profile'"
      register: server_profiles


  ## POLICIES

    # - name: Query Local User Policy
    #   cisco.intersight.intersight_rest_api:
    #     api_uri: "{{ intersight_endpoint }}"
    #     api_private_key: "{{ intersight_privatekey }}"
    #     api_key_id: "{{ intersight_apikeyid }}"
    #     resource_path: /iam/Policies
    #     query_params:
    #       $filter: "Name eq 'local-user-policy'"
    #   register: local_user_policy

    - name: Query BIOS Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /bios/Policies
        query_params:
          $filter: "Name eq 'bios-policy'"
      register: bios_policy

    - name: Query Boot Order Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /boot/PrecisionPolicies
        query_params:
          $filter: "Name eq 'boot-order-policy'"
      register: boot_order_policy

    - name: Query NTP Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /ntp/Policies
        query_params:
          $filter: "Name eq 'ntp-policy'"
      register: ntp_policy

    - name: Query IMC Access Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /access/Policy
        query_params:
          $filter: "Name eq 'imc-access-policy'"
      register: imc_access_policy

    - name: Query Virtual Media Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /vmedia/Policies
        query_params:
          $filter: "Name eq 'virtual-media-policy'"
      register: virtual_media_policy


  ## POOLS

    - name: Query IP Pools
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /ippools/Pools
        query_params:
          $filter: "Name eq 'dc1-ip-pool'"
      register: dc1_ip_pool
