---

- name: Cisco Intersight Query
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files: main.yml
  tasks:

  ## SERVERS


  ## TEMPLATES

    - name: Delete Server Profile derived from Template
      cisco.intersight.intersight_server_profile:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /server/Profiles
        query_params:
          $filter: "Name eq 'server-profile-template-{{ item }}'"
        state: absent
      loop: "{{ range(1, 3) | list }}"

    - name: Query Server Profile Template
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /server/ProfileTemplates
        query_params:
          $filter: "Name eq 'server-profile-template'"
      register: server_profile_templates


  ## PROFILES

    - name: Query Server Profile
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /server/Profiles
        query_params:
          $filter: "Name eq '{{ server_profile_name }}'"
      register: server_profiles


  ## POLICIES

    - name: Query Local User Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /iam/EndPointUserPolicies
        query_params:
          $filter: "Name eq '{{ local_user_policy_name }}'"
      register: local_user_policy

    - name: Query BIOS Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /bios/Policies
        query_params:
          $filter: "Name eq '{{ bios_policy_name }}'"
      register: bios_policy

    - name: Query Boot Order Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /boot/PrecisionPolicies
        query_params:
          $filter: "Name eq '{{ boot_order_policy_name }}'"
      register: boot_order_policy

    - name: Query NTP Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /ntp/Policies
        query_params:
          $filter: "Name eq '{{ ntp_policy_name }}'"
      register: ntp_policy

    - name: Query IMC Access Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /access/Policies
        query_params:
          $filter: "Name eq '{{ imc_access_policy_name }}'"
      register: imc_access_policy

    - name: Query Virtual Media Policy
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /vmedia/Policies
        query_params:
          $filter: "Name eq '{{ virtual_media_policy_name }}'"
      register: virtual_media_policy


  ## POOLS

    - name: Query IP Pools
      cisco.intersight.intersight_rest_api:
        api_uri: "{{ intersight_endpoint }}"
        api_private_key: "{{ intersight_privatekey }}"
        api_key_id: "{{ intersight_apikeyid }}"
        resource_path: /ippool/Pools
        query_params:
          $filter: "Name eq '{{ ip_pool_name }}'"
      register: dc1_ip_pool
